[package]
name = "klippy"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = "3.4"
tray-icon = "0.13"
winit = "0.29"
global-hotkey = "0.5"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
